version: '3.1'

services:
  postgresdb:
    image: postgres
    container_name: questionbank
    environment:
      POSTGRES_DB: questionbank
      POSTGRES_USER: questionbank
      POSTGRES_PASSWORD: questionbank
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/src/main/resources/db/upgrades:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
    depends_on:
      - postgresdb
